### ISSUE TITLE
Editable avatar border colors

### ISSUE THREAD

**Issue by RizkyRajitha** [RizkyRajitha/linkin#31]
currently avatar border color is hard coded to `#fff` color .

This has to be dynamic, so that the users can customize the color .

The new form input for color should be under the `Colors` tab in the `dashboard`

rough workflow

1. add new form Input with color type ([use bootstrap](https://getbootstrap.com/docs/5.1/forms/form-control/#color)), 
https://github.com/RizkyRajitha/linkin/blob/f92d38cb6eb07bcba3f445db568ccb76f50819f3/components/colorform.js#L99 

and register it with the react-form-hook `register` method passed `avatarBorderColor`  . destructure  `avatarBorderColor`  variable . (refer the existing implementation) https://github.com/RizkyRajitha/linkin/blob/f92d38cb6eb07bcba3f445db568ccb76f50819f3/components/colorform.js#L12

2. add new column to the `pagedata` relation in prisma with name `avatarBorderColor`  and type `String?    @db.VarChar`https://github.com/RizkyRajitha/linkin/blob/4f982b43707c20e8c55e7a98d5e800cdaae5199e/prisma/schema.prisma#L26 . 

3. migrate the modified prisma schema [prisma doc](https://www.prisma.io/docs/concepts/components/prisma-migrate) . (when migration dev you will need permission to create databases , if such problem occurs use docker postgres instance ).

4. destructure the new `avatarBorderColor`  variable and the pass it to the styles  
https://github.com/RizkyRajitha/linkin/blob/4f982b43707c20e8c55e7a98d5e800cdaae5199e/components/linkinthebiopage.js#L161

5. test whether everything works.

![avatarborder](https://user-images.githubusercontent.com/38534289/133753659-31245918-bfca-4aae-9935-2437a7d0a9e2.png)

**Comment by demonicirfan** [comment]
Can you assign this issue to me.

**Comment by RizkyRajitha** [comment]
hi @demonicirfan , 
you have assigned to #33 issue .

**Comment by davidzcode** [comment]
Hi, I would like to participate in this issue

**Comment by RizkyRajitha** [comment]
hi @davidzcode , 
appreciate your interest to contribute ,
i assigned this issue to you.

**Comment by RizkyRajitha** [comment]
@davidzcode  
everything works great , i merged the pr and now it's live on dev branch  👌 .

**Comment by davidzcode** [comment]
Nice to hear that 🔥
