### ISSUE TITLE
Convert fetch api calls to SWR

### ISSUE THREAD

**Issue by RizkyRajitha** [RizkyRajitha/linkin#32]
Convert all the `fetch` api calls to  [swr](https://swr.vercel.app/)  in [formwrapper.js](https://github.com/RizkyRajitha/linkin/blob/f92d38cb6eb07bcba3f445db568ccb76f50819f3/components/formwrapper.js) file . 

check whether everything works as expected , and nothing harmed .

**Comment by DireWolf707** [comment]
I would like to contribute to this issue in Hacktoberfest. Can you assign this issue to me?

**Comment by brownboycodes** [comment]
I would like to try this out

**Comment by RizkyRajitha** [comment]
> I would like to contribute to this issue in Hacktoberfest. Can you assign this issue to me?

since this issue is already addressed by @brownboycodes ,i will make a separate issue for you , can you check that out @DireWolf707 .
