### ISSUE TITLE
Create test cases for react ui components  

### ISSUE THREAD

**Issue by RizkyRajitha** [RizkyRajitha/linkin#33]
i am not familiar  with this area , so i cannot help much on this issue .
basically i need to test the react ui components whether they render correctly on correct circumstances.  

refer to the bellow links that might help

https://reactjs.org/docs/testing.html

https://testing-library.com/docs/react-testing-library/intro/

**Comment by demonicirfan** [comment]
Hii I am also new to testing I don't know too much about it but I will learn and work on it can you assign it to me, I will get to learn also and contribute too.

**Comment by RizkyRajitha** [comment]
hi @demonicirfan ,

appreciate your interest to contribute , you can work on this issue.

**Comment by demonicirfan** [comment]
yes, sure I will start working on this issue from now. It will take me some time. Is there any issue if I take time of around 2 weeks.

**Comment by RizkyRajitha** [comment]
@demonicirfan no problem take your time but try to update your progress so that i can know this issue is not stale
thanks .

**Comment by demonicirfan** [comment]
yes definitely i will keep on updating you

**Comment by demonicirfan** [comment]
I don't think i can do it I'm not getting time to learn that, I am unassigning myself this issue

**Comment by RizkyRajitha** [comment]
@demonicirfan oh sorry to here that ,
feel free to to checkout other issues is you like

**Comment by Travis544** [comment]
Hi, I would like to work on this assignment

**Comment by Dxuian** [comment]
still open ?

**Comment by RizkyRajitha** [comment]
unfortunately no will close this
