### ISSUE TITLE
Add support to mailto links

### ISSUE THREAD

**Issue by dubisdev** [RizkyRajitha/linkin#53]
Currently only links with structure "http: // ....." are supported.

HTML also allows adding "mailto: email address" links (like [this](mailto:dubisdev@gmail.com)), to link to email forms easily. It would be interesting to add support for them.

I can do it 🚀

**Comment by RizkyRajitha** [comment]
hi @dubisdev ,

that is a good feature addition , can you draft a design , so we can discuss and implement it . i think this will involve creating a new column in database to link type also .
